### PR TITLE
fix task strings

### PR DESCRIPTION
**Pull request by hdefazio**
Removes underscores from the task steps

### CODE REVIEW

**Comment by hdefazio** [comment]
@joshanderson-kw

**Comment by joshanderson-kw** [comment]
Has this been tested with the activity detector? I get errors when running with the activity detector output, but it works with the keyboard input.

Should we merge #83 first and add try this one?

**Comment by Purg** [comment]
> Has this been tested with the activity detector? I get errors when running with the activity detector output, but it works with the keyboard input.
> 
> Should we merge #83 first and then try this one? @Purg

Yeah, let's get that in and then rebase this on master and test again.

**Comment by hdefazio** [comment]
> > Has this been tested with the activity detector? I get errors when running with the activity detector output, but it works with the keyboard input.
> > Should we merge #83 first and then try this one? @Purg
> 
> Yeah, let's get that in and then rebase this on master and test again.

This also depends on #81, can we get that merged?

**Comment by hdefazio** [comment]
ok, this is tested and rebased on master

**Comment by joshanderson-kw** [comment]
I still see one of my old commits here. Is that why `_task_lock` was removed?

**Comment by hdefazio** [comment]
Closing in favor of #85

**Pull request closed without merging**
