### PR TITLE
Add Activity TCN classifier node and support

### PR DESCRIPTION
**Pull request by Purg**

### CODE REVIEW

**Comment by Purg** [comment]
@cameron-a-johnson @hdefazio This is the branch that adds the load/norm/predict functions and ROS node for the TCN activity classifier. PTAL.

**Comment by Purg** [comment]
Working on resolving the conflict. Since it has to do with the environment, I'm making sure poetry can resolve successfully and re-lock this branch's additions

**Comment by Purg** [comment]
Also quickly addressed the missing Python dependency and CI config issue that was causing the pytests to fail to collect and run.

**Comment by cameron-a-johnson** [comment]
I approve this merge btw! Upon successful CI runs let's merge this branch

**Pull request merged**
