### PR TITLE
New/updated features in demo-ui

### PR DESCRIPTION
**Pull request by hdefazio**
- [x] Removed done button
- [x] Add task ids to task list
- [x] Added back the colors in activity classification chart
- [x] Add probability of recipe finish to a chart
- [x] Filter displayed bounding boxes to top 5

### CODE REVIEW

**Comment by hdefazio** [comment]
Depends on #142

**Comment by hdefazio** [comment]
@joshanderson-kw Could you check/review [ros/angel_debug/angel_debug/nodes/simple_2d_detection_overlay.cxx](https://github.com/PTG-Kitware/angel_system/pull/148/files#diff-78b8ec8b62e7e4a6a6935a745463b635b11da663bea939004754142e7c9203aa)?

**Comment by joshanderson-kw** [comment]
> @joshanderson-kw Could you check/review [ros/angel_debug/angel_debug/nodes/simple_2d_detection_overlay.cxx](https://github.com/PTG-Kitware/angel_system/pull/148/files#diff-78b8ec8b62e7e4a6a6935a745463b635b11da663bea939004754142e7c9203aa)?

Looks good to me!

**Comment by hdefazio** [comment]
Closed in #153

**Pull request closed without merging**
